name: "cANs Linker Action"
description: "Link pull requests to Notion ticket based on branch name"
inputs:
  notion-token:
    description: API token for the Notion integration
  stories-db-id:
    description: ID of the stories database
  github-token:
    description: API token for GitHub
outputs:
  ticket-id:
    description: "ID of the Notion ticket"
  ticket-name:
    description: "Name of the Notion ticket"
  ticket-url:
    description: "URL to the Notion ticket"
runs:
  using: "node16"
  main: "dist/index.js"
